---
title: "Proyecto Dashboard FSS"
author: "Fernando Sánchez Sánchez"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}

if(!require(dplyr)){install.packages('dplyr')
  library(dplyr)
}

if(!require(flexdashboard)){install.packages('flexdashboard')
  library(flexdashboard)
}

if(!require(tidyverse)){install.packages('tidyverse')
  library(tidyverse)
}

if(!require(maps)){install.packages('maps')
  library(maps)
}

if(!require(DT)){install.packages('DT')
  library(DT)
}

if(!require(ggplot2)){install.packages('ggplot2')
  library(ggplot2)
}

if(!require(readr)){install.packages('readr')
  library(readr)
}

if(!require(shiny)){install.packages('shiny')
  library(shiny)
}

if(!require(shinydashboard)){install.packages('shinydashboard')
  library(shinydashboard)
}


```

```{r}


datos  <- read_csv("Dashboard/Código/Datos depurados.csv")

```


Página 1 
===================


Column {data-width=350}
-----------------------------------------------------------------------

### Mapa de europa

```{r}
datos <- select(datos, idno, nwspol, netusoft, netustm, ppltrst, pplfair, pplhlp, hhmmb, gndr, agea, cntry, maritalb, chldhhe, domicil, eduyrs)

densidad1 <- density(datos$nwspol, na.rm = TRUE)
plot(densidad1, main = "Gráfico de Densidad - nwspol", xlab = "nwspol", ylab = "Densidad")








```

Column {data-width=250}
-----------------------------------------------------------------------

### Medias por sexo

```{r}
# Preparamos las variables
vars <- c('ppltrst','pplfair','pplhlp')


# Calcular las medias redondeadas a un decimal por género 
datos.s <- aggregate(cbind(ppltrst, pplfair, pplhlp) ~ gndr, data = datos, FUN = function(x) round(mean(x), 1))


df <- datos.s %>%
  select(gndr, ppltrst:pplhlp) %>%
  pivot_longer(names_to = "variable", values_to = "Media", -gndr)


ggplot(df, aes(x = variable, y = Media, fill = gndr)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Media), vjust = -0.5, position = position_dodge(width = 1), color = "black", size = 3) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Confianza", "Honestidad", "Ayuda")) +
  labs(fill = "Género") +
  ylim(0, 10) +
  theme_minimal()+
  theme(legend.position = c(0.50, 0.80), legend.direction = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5, title.vjust = 0.5,
                             label.position = "right", label.hjust = 0.5, label.vjust = 0.5,
                             keywidth = 0.5, keyheight = 1, nrow = 2))
```


### Medias por menores en el hogar

```{r}
# Preparamos las variables
vars <- c('ppltrst','pplfair','pplhlp')


# Calcular las medias redondeadas a un decimal por género 
datos.h <- aggregate(cbind(ppltrst, pplfair, pplhlp) ~ chldhhe, data = datos, FUN = function(x) round(mean(x), 1))


df <- datos.h %>%
  select(chldhhe, ppltrst:pplhlp) %>%
  pivot_longer(names_to = "variable", values_to = "Media", -chldhhe)


ggplot(df, aes(x = variable, y = Media, fill = chldhhe)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Media), vjust = -0.5, position = position_dodge(width = 1), color = "black", size = 3) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Confianza", "Honestidad", "Ayuda")) +
  labs(fill = "Menores en el hogar") +
  ylim(0, 10) +
  theme_minimal()+
  theme(legend.position = c(0.50, 0.80), legend.direction = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5, title.vjust = 0.5,
                             label.position = "right", label.hjust = 0.5, label.vjust = 0.5,
                             keywidth = 0.5, keyheight = 1, nrow = 2))
```


Column {data-width=250}
-----------------------------------------------------------------------

### Medias por estado civil

```{r}
# Preparamos las variables
vars <- c('ppltrst','pplfair','pplhlp')


# Calcular las medias redondeadas a un decimal por estado civil
datos.e <- aggregate(cbind(ppltrst, pplfair, pplhlp) ~ maritalb, data = datos, FUN = function(x) round(mean(x), 1))


df <- datos.e %>%
  select(maritalb, ppltrst:pplhlp) %>%
  pivot_longer(names_to = "variable", values_to = "Media", -maritalb)


ggplot(df, aes(x = variable, y = Media, fill = maritalb)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Media), vjust = -0.5, position = position_dodge(width = 1), color = "black", size = 2.5) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Confianza", "Honestidad", "Ayuda")) +
  labs(fill = "Estado civil") +
  ylim(0, 10) +
  theme_minimal()+
  theme(legend.position = c(0.50, 0.80), legend.direction = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5, title.vjust = 0.5,
                             label.position = "right", label.hjust = 0.5, label.vjust = 0.5,
                             keywidth = 0.5, keyheight = 1, nrow = 2))
```

### Medias por lugar de residencia

```{r}
# Preparamos las variables
vars <- c('ppltrst','pplfair','pplhlp')


# Calcular las medias redondeadas a un decimal por lugar de residencia 
datos.l <- aggregate(cbind(ppltrst, pplfair, pplhlp) ~ domicil, data = datos, FUN = function(x) round(mean(x), 1))


df <- datos.l %>%
  select(domicil, ppltrst:pplhlp) %>%
  pivot_longer(names_to = "variable", values_to = "Media", -domicil)


ggplot(df, aes(x = variable, y = Media, fill = domicil)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Media), vjust = -0.5, position = position_dodge(width = 1), color = "black", size = 3) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Confianza", "Honestidad", "Ayuda")) +
  labs(fill = "Lugar de residencia") +
  ylim(0, 10) +
  theme_minimal()+
  theme(legend.position = c(0.50, 0.80), legend.direction = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5, title.vjust = 0.5,
                             label.position = "right", label.hjust = 0.5, label.vjust = 0.5,
                             keywidth = 0.5, keyheight = 1, nrow = 2))
```

Tablas 
===================

```{r}
datos$grupo_edad
datos$etapa_educativa

```

```{r}
datos.medias <- aggregate(cbind(ppltrst, pplfair, pplhlp) ~ cntry + gndr + grupo_edad + etapa_educativa + chldhhe + domicil + maritalb, data = datos, FUN = function(x) round(mean(x), 1))

#datatable(datos.medias,
          caption = "Tabla muy buena",
          rownames = T,
          filter = "top",
          options = list(page.lenght = 25))

```


Página 3 
===================